# Generated by Django 2.2.3 on 2020-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
