# Generated by Django 2.2.3 on 2020-03-14 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_nav_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
            ],
        ),
    ]
