# Generated by Django 2.2.3 on 2020-03-16 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterField(
            model_name='log',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
