# Generated by Django 2.2.3 on 2020-03-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200316_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
