# Generated by Django 2.2.3 on 2020-03-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200322_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='size',
            field=models.SmallIntegerField(default=6),
        ),
    ]
